doctrine:
    dbal:

        default_connection: engineblock
        connections:
            engineblock:
                #                schema_filter: ~^(?!group_|virtual_|service_provider_|saml_persistent_id|sso_provider_roles|log_logins|db_changelog|consent)~
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                dbname:   "%database.dbname%"
                host:     "%database.host%"
                port:     "%database.port%"
                user:     "%database.user%"
                password: "%database.password%"
                charset:  UTF8
                # when true, queries are logged to a 'doctrine' monolog channel
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
                server_version: '10.6.0-MariaDB'
                mapping_types:
                    enum: string
        types:
            engineblock_collab_person_id: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonIdType
            engineblock_collab_person_uuid: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonUuidType
            engineblock_metadata_coins: OpenConext\EngineBlockBundle\Doctrine\Type\MetadataCoinType
            engineblock_metadata_mdui: OpenConext\EngineBlockBundle\Doctrine\Type\MetadataMduiType

            engineblock_logo: OpenConext\EngineBlockBundle\Doctrine\Type\LogoType
            engineblock_organization: OpenConext\EngineBlockBundle\Doctrine\Type\OrganizationType
            engineblock_certificate_array: OpenConext\EngineBlockBundle\Doctrine\Type\CertificateArrayType
            engineblock_contact_person_array: OpenConext\EngineBlockBundle\Doctrine\Type\ContactPersonArrayType
            engineblock_service: OpenConext\EngineBlockBundle\Doctrine\Type\ServiceType
            engineblock_service_array: OpenConext\EngineBlockBundle\Doctrine\Type\ServiceArrayType
            engineblock_indexed_service_array: OpenConext\EngineBlockBundle\Doctrine\Type\IndexedServiceArrayType
            engineblock_requested_attribute_array: OpenConext\EngineBlockBundle\Doctrine\Type\RequestedAttributeArrayType
            engineblock_shib_md_scope_array: OpenConext\EngineBlockBundle\Doctrine\Type\ShibMdScopeArrayType
            engineblock_attribute_release_policy: OpenConext\EngineBlockBundle\Doctrine\Type\AttributeReleasePolicyType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        enable_lazy_ghost_objects: true
        entity_managers:
            engineblock:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: ~
                # Opt-in to new mapping driver mode as of Doctrine ORM 2.16, https://github.com/doctrine/orm/pull/10455
                report_fields_where_declared: true
                mappings:
                    # An array of mappings, which may be a bundle name or something else
                    Authentication:
                        mapping:   true
                        type:      attribute
                        dir:       "%kernel.project_dir%/src/OpenConext/EngineBlockBundle/Authentication"
                        prefix:    OpenConext\EngineBlockBundle\Authentication
                        is_bundle: false
                    Metadata:
                        mapping:   true
                        type:      attribute
                        dir:       "%kernel.project_dir%/src/OpenConext/EngineBlock/Metadata"
                        prefix:    OpenConext\EngineBlock\Metadata
                        is_bundle: false
                dql:
                    string_functions:
                        md5: OpenConext\EngineBlockBundle\Doctrine\DqlFunction\Md5
