parameters:
    # based on the hardcoded value in
    # https://github.com/OpenConext/OpenConext-engineblock/blob/
    #   4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L242
    locale: en
    container.autowiring.strict_mode: true

    # This value is used as cache-buster, replaced by the release script
    asset_version: "#ASSET_VERSION#"

framework:
    secret: '%env(APP_SECRET)%'
    esi: false
    translator:
        fallbacks: [ "%locale%" ]
        paths:
            - '%kernel.project_dir%/languages'
            - '%kernel.project_dir%/theme/base/translations'
            - '%kernel.project_dir%/theme/%theme.name%/translations'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale: "%locale%"
    trusted_hosts: ~

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # ID of the service used for session storage
        # NULL means that Symfony uses PHP default session mechanism
        handler_id: null
        storage_factory_id: session.storage.factory.native

    fragments: false
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    error_controller: 'Symfony\Component\HttpKernel\Controller\ErrorController::show'
    router:
        utf8: true
