language: php

dist: xenial

php:
  - 5.6
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
  - env: COMMAND="functional-tests-wip"

sudo: true # sudo is required for behat

env:
  matrix:
    - COMMAND="functional-tests"
    - COMMAND="functional-tests-wip"
    - COMMAND="functional-tests-selenium"
    - COMMAND="code-quality-ci"
    - COMMAND="security-tests"
    - COMMAND="composer-validate"
  global:
    - SYMFONY_ENV=test
    - ENGINEBLOCK_ENV=test
    - ANT_OPTS=-Xmx256m # ensure we got enough memory for ant

cache:
  directories:
    - ~/.composer/cache/files

before_install:
  - mysql -e "create database IF NOT EXISTS eb_test;" -uroot
  - mysql -uroot -e "CREATE USER 'eb_testrw'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -uroot -e "GRANT ALL ON eb_test.* TO 'eb_testrw'@'localhost';"

before_script:
  - phpenv config-add .travis.php.ini
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then printf "\n" | pecl uninstall apcu; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then printf "\n" | pecl install apcu-4.0.10; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sed -i 's,apc,array,' ~/build/OpenConext/OpenConext-engineblock/app/config/config.yml; fi
  - sudo ln -s "$(pwd)"/ci/travis/files/ /etc/openconext
  - mkdir -p /tmp/engineblock/cache/test
  - mkdir -p /tmp/engineblock/logs/test
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi ant
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias ssl
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f ci/travis/vhost-apache /etc/apache2/sites-available/default-ssl.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default-ssl.conf
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - sudo a2dissite 000-default
  - sudo a2ensite default-ssl
  - sudo service apache2 restart
  - sudo mkdir -p /opt/selenium && wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar && sudo mv selenium-server-standalone-2.53.1.jar /opt/selenium/
  - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && rm chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /opt/selenium/chromedriver
  - sudo /usr/bin/java -jar /opt/selenium/selenium-server-standalone-2.53.1.jar -Dwebdriver.chrome.driver=/opt/selenium/chromedriver -host 127.0.0.1 -port 4444 &
  - composer self-update
  - composer config secure-http false
  - composer install --prefer-dist -n -o
  - app/console cache:clear --env=test
  - npm install --prefix=theme
  - npm install grunt-cli -g
  - cd theme && grunt && cd ..

script:
  - ant $COMMAND

branches:
  only:
    - 5.x-dev
    - master
    - release/5.8
    - feature/allow-repost-on-consent

after_failure:
  - sudo tail -500 /var/log/apache2/error.log
  - sudo tail -500 /var/log/apache2/access.log
  - cat ~/build/OpenConext/OpenConext-engineblock/app/logs/test/test.log
  - sudo tail -500 /var/log/syslog
  - sudo tail -500 /tmp/selenium-log

addons:
  hosts:
    - engine.vm.openconext.org
  mariadb: '10.2'
  chrome: stable
