imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: logging.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    # based on the hardcoded value in
    # https://github.com/OpenConext/OpenConext-engineblock/blob/
    #   4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L242
    locale: en

    # This value is used as cache-buster, replaced by the release script
    asset_version: "#ASSET_VERSION#"

open_conext_engine_block:
    features:
        api.metadata_push:   "%feature_api_metadata_push%"
        api.consent_listing: "%feature_api_consent_listing%"
        api.consent_remove: "%feature_api_consent_remove%"
        api.metadata_api:    "%feature_api_metadata_api%"
        api.deprovision:     "%feature_api_deprovision%"
        eb.encrypted_assertions: "%feature_eb_encrypted_assertions%"
        eb.encrypted_assertions_require_outer_signature: "%feature_eb_encrypted_assertions_require_outer_signature%"
        eb.run_all_manipulations_prior_to_consent: "%feature_run_all_manipulations_prior_to_consent%"
        eb.block_user_on_violation: "%feature_block_user_on_violation%"
        eb.enable_sso_notification: "%feature_enable_sso_notification%"
        eb.feature_enable_consent: "%feature_enable_consent%"
        eb.enable_sso_session_cookie: "%feature_enable_sso_session_cookie%"
        eb.feature_enable_idp_initiated_flow: "%feature_enable_idp_initiated_flow%"
        eb.stepup.sfo.override_engine_entityid: "%feature_stepup_sfo_override_engine_entityid%"


framework:
    esi:             false
    translator:
        fallbacks: ["%locale%"]
        paths:
          - '%kernel.project_dir%/languages'
          - '%kernel.project_dir%/theme/base/translations'
          - '%kernel.project_dir%/theme/%theme.name%/translations'
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       false
    http_method_override: true
    mailer:
        transports:
            smtp: "smtp://%mailer_user%:%mailer_password%@%mailer_host%:%mailer_port%"
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.array
            doctrine.system_cache_pool:
                adapter: cache.adapter.array

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.project_dir%/theme/%theme.name%/templates/modules": theme
        "%kernel.project_dir%/theme/%theme.name%/templates/layouts": themeLayouts
        "%kernel.project_dir%/theme/%theme.name%/images": images
        "%kernel.project_dir%/theme/base/templates/modules": theme
        "%kernel.project_dir%/theme/base/templates/layouts": themeLayouts
        "%kernel.project_dir%/theme/base/images": images
    globals:
        assetsVersion: "%asset_version%"
        defaultTitle: "%view_default_title%"
        defaultHeader: "%view_default_header%"
        defaultLogo: "%view_default_logo%"
        envName: "%env_name%"
        envRibbonColor: "%env_ribbon_color%"

doctrine:
    dbal:
        default_connection: engineblock
        connections:
            engineblock:
#                schema_filter: ~^(?!group_|virtual_|service_provider_|saml_persistent_id|sso_provider_roles|log_logins|db_changelog|consent)~
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                dbname:   "%database.dbname%"
                host:     "%database.host%"
                port:     "%database.port%"
                user:     "%database.user%"
                password: "%database.password%"
                charset:  UTF8
                # when true, queries are logged to a 'doctrine' monolog channel
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
                server_version: 5.5
                mapping_types:
                    enum: string
        types:
            engineblock_collab_person_id: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonIdType
            engineblock_collab_person_uuid: OpenConext\EngineBlockBundle\Doctrine\Type\CollabPersonUuidType
            engineblock_metadata_coins: OpenConext\EngineBlockBundle\Doctrine\Type\MetadataCoinType
            engineblock_metadata_mdui: OpenConext\EngineBlockBundle\Doctrine\Type\MetadataMduiType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        entity_managers:
            engineblock:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                metadata_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache_provider
                connection: ~
                mappings:
                    # An array of mappings, which may be a bundle name or something else
                    Authentication:
                        mapping:   true
                        type:      annotation
                        dir:       "%kernel.project_dir%/src/OpenConext/EngineBlockBundle/Authentication"
                        prefix:    OpenConext\EngineBlockBundle\Authentication
                        is_bundle: false
                    Metadata:
                        mapping:   true
                        type:      annotation
                        dir:       "%kernel.project_dir%/src/OpenConext/EngineBlock/Metadata"
                        prefix:    OpenConext\EngineBlock\Metadata
                        is_bundle: false
                dql:
                    string_functions:
                        md5: OpenConext\EngineBlockBundle\Doctrine\DqlFunction\Md5

doctrine_migrations:
    migrations_paths:
        'OpenConext\EngineBlock\Doctrine\Migrations': '%kernel.project_dir%/database/DoctrineMigrations'
    #    dir_name:   "%kernel.project_dir%/database/DoctrineMigrations"
    #    namespace:  OpenConext\EngineBlock\Doctrine\Migrations
    storage:
        table_storage:
            table_name: migration_versions
#    name:       OpenConext EngineBlock Migrations

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'
    app.mailer:
        alias: Symfony\Component\Mailer\MailerInterface
        public: true
