imports:
    - { resource: functional_testing.yml }
    - { resource: config_dev.yml }

# Test service DI container overwrites (used for test and ci envs)
services:
    engineblock.features:
        class: OpenConext\EngineBlockBundle\Configuration\TestFeatureConfiguration
        public: true

    engineblock.twig.extension.global_site_notice:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\FunctionalTestingGlobalSiteNotice
        arguments:
            - "@request_stack"
            - "%global.site_notice.allowed.tags%"
        tags:
            - { name: 'twig.extension' }


framework:
    test: ~
    translator:
        fallbacks: ["%locale%"]
        paths:
            - '%kernel.root_dir%/../languages'
            - '%kernel.root_dir%/../theme/base/translations'
            - '%kernel.root_dir%/../theme/%theme.name%/translations'
            - '%kernel.root_dir%/../src/OpenConext/EngineBlockFunctionalTestingBundle/Resources/languages'
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSION
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: true
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# override the logging settings so that we can log to readable files on github actions
monolog:
    channels: ["%logger.channel%", "authentication"]
    handlers:
        main:
            type: fingers_crossed
            activation_strategy: engineblock.logger.manual_or_error_activation_strategy
            passthru_level: "%logger.fingers_crossed.passthru_level%"
            handler: file
            channels: ['!event']
        file:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  DEBUG

security:
    providers:
        in_memory:
            memory:
                users:
                    no_roles:
                        password: no_roles
                        roles: []

doctrine:
    dbal:
        default_connection: engineblock_test
        connections:
            engineblock_test:
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                server_version: 5.5
                dbname:   "%database.test.dbname%"
                host:     "%database.test.host%"
                port:     "%database.test.port%"
                user:     "%database.test.user%"
                password: "%database.test.password%"

twig:
    strict_variables: true
