imports:
    - { resource: parameters.yml }
    - { resource: ini_parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    # based on the hardcoded value in
    # https://github.com/OpenConext/OpenConext-engineblock/blob/
    #   4102bffe58a9ecbce3c7c934e0aa8ece46efcf82/library/EngineBlock/Application/Bootstrapper.php#L242
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [192.168.1.1, 10.0.0.1]
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

monolog:
    channels: [engineblock]
    handlers:
        main:
            type: fingers_crossed
            activation_strategy: engineblock.bridge.log.manual_or_error_activation_strategy
            passthru_level: NOTICE
            handler: syslog
        syslog:
            type:      syslog
            ident:     EBLOG
            formatter: engineblock.bridge.log.additional_info_formatter
