imports:
    - { resource: functional_testing.yml }
    - { resource: config_test.yml }
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
doctrine:
    dbal:
        default_connection: engineblock_test
        connections:
            engineblock:
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                server_version: 5.5
                dbname:   "%database.dbname%"
                host:     "db.vm.openconext.org"
                port:     "%database.port%"
                user:     "%database.user%"
                password: "%database.password%"
            engineblock_test:
                driver:   pdo_mysql         # This must be PDO until all database interaction runs through doctrine
                server_version: 5.5
                dbname:   "%database.test.dbname%"
                host:     "db-test.vm.openconext.org"
                port:     "%database.test.port%"
                user:     "%database.test.user%"
                password: "%database.test.password%"
