services:
    engineblock.listener.execution_time_tracker:
        class: OpenConext\EngineBlockBundle\EventListener\ExecutionTimeTracker
        arguments:
            - "@debug.stopwatch"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: startTracking, priority: 1000 }

    engineblock.listener.error_response_time_padding:
        class: OpenConext\EngineBlockBundle\EventListener\ErrorResponseTimePaddingListener
        arguments:
            - "@engineblock.listener.execution_time_tracker"
            - "@router"
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
            - "@engineblock.minimum_execution_time_on_invalid_response"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 1000 }

    engineblock.listener.redirect_to_feedback_page_exception:
        class: OpenConext\EngineBlockBundle\EventListener\RedirectToFeedbackPageExceptionListener
        arguments:
            - "@engineblock.compat.application"
            - "@router"
            - "@engineblock.bridge.error_reporter"
            - "@engineblock.compat.logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    engineblock.listener.api_http_exception_listener:
        class: OpenConext\EngineBlockBundle\EventListener\ApiHttpExceptionListener
        arguments:
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    engineblock.listener.not_found_http_exception:
        class: OpenConext\EngineBlockBundle\EventListener\NotFoundHttpExceptionListener
        arguments:
            - "@engineblock.compat.application"
            - "@engineblock.compat.view"
            - "@engineblock.compat.logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 25 }

    engineblock.listener.fallback_exception:
        class: OpenConext\EngineBlockBundle\EventListener\FallbackExceptionListener
        arguments:
            - "@engineblock.compat.application"
            - "@engineblock.compat.view"
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -200 }
