# also see bridge_event_listeners.yml for event listeners that provide bridge functionality
services:
    engineblock.listener.execution_time_tracker:
        class: OpenConext\EngineBlockBundle\EventListener\ExecutionTimeTracker
        arguments:
            - "@debug.stopwatch"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: startTracking, priority: 1000 }

    engineblock.listener.error_response_time_padding:
        class: OpenConext\EngineBlockBundle\EventListener\ExecutionTimePaddingListener
        arguments:
            - "@engineblock.listener.execution_time_tracker"
            - "@router"
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
            - "@engineblock.minimum_execution_time_on_invalid_received_response"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 1000 }

    engineblock.listener.redirect_to_feedback_page_exception:
        class: OpenConext\EngineBlockBundle\EventListener\RedirectToFeedbackPageExceptionListener
        arguments:
            - "@engineblock.compat.application"
            - "@router"
            - "@engineblock.bridge.error_reporter"
            - "@engineblock.compat.logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    engineblock.listener.api_http_exception_listener:
        class: OpenConext\EngineBlockBundle\EventListener\ApiHttpExceptionListener
        arguments:
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    engineblock.listener.not_found_http_exception:
        class: OpenConext\EngineBlockBundle\EventListener\NotFoundHttpExceptionListener
        arguments:
            - "@engineblock.compat.application"
            - "@twig"
            - "@engineblock.compat.logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 25 }

    engineblock.listener.method_not_allowed_http_exception:
        class: OpenConext\EngineBlockBundle\EventListener\MethodNotAllowedHttpExceptionListener
        arguments:
            - "@twig"
            - "@engineblock.compat.logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 25 }

    engineblock.listener.fallback_exception:
        class: OpenConext\EngineBlockBundle\EventListener\FallbackExceptionListener
        arguments:
            - "@engineblock.compat.logger"
            - "@engineblock.bridge.error_reporter"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -200 }

    engineblock.listener.authentication_state_initializer:
        class: OpenConext\EngineBlockBundle\EventListener\AuthenticationStateInitializer
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 10 }

    engineblock.listener.locale:
        class: OpenConext\EngineBlockBundle\EventListener\LocaleListener
        arguments:
            - '@engineblock.locale_provider'
            - '@engineblock.locale.cookie_factory'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 15 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 15 }
