services:
    OpenConext\EngineBlock\Xml\:
        resource: '../../../EngineBlock/Xml'
        exclude: '../../../EngineBlock/Xml/ValueObjects'
        autowire: true
        autoconfigure: true

    openconext.monitor.database_health_check:
        class: OpenConext\EngineBlockBundle\HealthCheck\DoctrineConnectionHealthCheck
        arguments:
            - "%monitor_database_health_check_query%"
        calls:
            - [ setEntityManager, ['@?doctrine.orm.entity_manager']]
        tags:
            - { name: openconext.monitor.health_check }

    engineblock.minimum_execution_time_on_invalid_received_response:
        class: OpenConext\EngineBlockBundle\Value\ExecutionTime
        factory: [ OpenConext\EngineBlockBundle\Value\ExecutionTime, "of" ]
        arguments:
            - "%minimum_execution_time_on_invalid_received_response%"

    engineblock.configuration.stepup.endpoint:
        class: OpenConext\EngineBlock\Stepup\StepupEndpoint
        arguments:
            - "%stepup.gateway.sfo.entity_id%"
            - "%stepup.gateway.sfo.sso_location%"
            - "%stepup.gateway.sfo.key_file%"

    engineblock.configuration.stepup.loa_repository:
        class: OpenConext\EngineBlock\Metadata\LoaRepository
        arguments:
            - "%stepup.loa.mapping%"

    engineblock.configuration.stepup.gateway_loa_mapping:
        class: OpenConext\EngineBlock\Stepup\StepupGatewayLoaMapping
        arguments:
            - "%stepup.loa.mapping%"
            - "%stepup.loa.loa1%"
            - "@engineblock.configuration.stepup.loa_repository"

    engineblock.request.request_id_generator:
        public: false
        class: OpenConext\EngineBlock\Request\UniqidGenerator

    engineblock.request.request_id:
        class: OpenConext\EngineBlock\Request\RequestId
        arguments:
            - "@engineblock.request.request_id_generator"
        public: true

    engineblock.security.http_basic_entry_point:
        class: OpenConext\EngineBlockBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"

    engineblock.service.authentication_state_helper:
        class: OpenConext\EngineBlock\Service\AuthenticationStateHelper
        arguments:
            - "@session"

    engineblock.service.processing_state_helper:
        class: OpenConext\EngineBlock\Service\ProcessingStateHelper
        arguments:
            - "@session"

    engineblock.service.stepup.gateway_callout_helper:
        class: OpenConext\EngineBlock\Stepup\StepupGatewayCallOutHelper
        arguments:
            - "@engineblock.configuration.stepup.gateway_loa_mapping"
            - "@engineblock.configuration.stepup.endpoint"
            - "@engineblock.configuration.stepup.loa_repository"
            - "@logger"

    engineblock.service.consent:
        class: OpenConext\EngineBlock\Service\ConsentService
        arguments:
            - "@engineblock.repository.consent"
            - "@engineblock.service.metadata"
            - "@engineblock.compat.logger"

    engineblock.service.deprovision:
        class: OpenConext\EngineBlock\Service\DeprovisionService
        arguments:
            - "@engineblock.repository.consent"
            - "@engineblock.authentication.user_directory"
            - "@engineblock.repository.saml_persistent_id"
            - "@engineblock.repository.service_provider_uuid"

    engineblock.service.metadata:
        class: OpenConext\EngineBlock\Service\MetadataService
        arguments:
            - "@engineblock.compat.repository.metadata"
            - "@engineblock.compat.logger"

    engineblock.service.mfa_helper:
        class: OpenConext\EngineBlock\Service\MfaHelper
        arguments:
            - "@engineblock.compat.logger"
            - "@engineblock.metadata.repository.cached_doctrine"

    engineblock.service.time_provider:
        class: OpenConext\EngineBlock\Service\TimeProvider\TimeProvider

    engineblock.service.sso_notification:
        class: OpenConext\EngineBlock\Service\SsoNotificationService
        arguments:
            - "%sso_notification_encryption_key%"
            - "%sso_notification_encryption_key_salt%"
            - "%sso_notification_encryption_algorithm%"
            - "@engineblock.compat.logger"

    engineblock.service.sso_session:
        class: OpenConext\EngineBlock\Service\SsoSessionService
        arguments:
            - "%sso_session_cookie_max_age%"
            - "%cookie.locale.domain%"
            - "%cookie.path%"
            - "@engineblock.service.cookie"
            - "@engineblock.compat.logger"

    engineblock.service.cookie:
        class: OpenConext\EngineBlock\Service\CookieService

    engineblock.factory.service_provider_factory:
        class: OpenConext\EngineBlock\Metadata\Factory\Factory\ServiceProviderFactory
        arguments:
            - '@engineblock.compat.metadata.definitions'
            - '@OpenConext\EngineBlock\Metadata\X509\KeyPairFactory'
            - '@OpenConext\EngineBlock\Metadata\Factory\ValueObject\EngineBlockConfiguration'
            - '@engineblock.url_provider'
            - '@engineblock.features'
            - '%stepup.sfo.override_engine_entityid%'

    OpenConext\EngineBlock\Metadata\Factory\ValueObject\EngineBlockConfiguration:
        public: false
        arguments:
            - '@translator'
            - '%email_request_access_address%'
            - '%view_default_header%'
            - '%hostname%'
            - '%view_default_logo%'
            - '%view_default_logo_width%'
            - '%view_default_logo_height%'

    engineblock.factory.identity_provider_factory:
        class: OpenConext\EngineBlock\Metadata\Factory\Factory\IdentityProviderFactory
        arguments:
            - '@OpenConext\EngineBlock\Metadata\X509\KeyPairFactory'
            - '@OpenConext\EngineBlock\Metadata\Factory\ValueObject\EngineBlockConfiguration'
            - '@engineblock.url_provider'

    OpenConext\EngineBlock\Xml\MetadataRenderer:
        arguments:
            - "@engineblock.language_support_provider"
            - "@twig"
            - "@engineblock.compat.saml2_id_generator"
            - "@OpenConext\\EngineBlock\\Metadata\\X509\\KeyPairFactory"
            - "@OpenConext\\EngineBlock\\Xml\\DocumentSigner"
            - "@engineblock.service.time_provider"
            - "%metadata_add_requested_attributes%"

    OpenConext\EngineBlock\Xml\MetadataProvider:
        arguments:
            - '@OpenConext\EngineBlock\Xml\MetadataRenderer'
            - '@engineblock.factory.service_provider_factory'
            - '@engineblock.factory.identity_provider_factory'
            - '@OpenConext\EngineBlock\Metadata\X509\KeyPairFactory'
            - '@engineblock.metadata.repository.idps_metadata'

    engineblock.authentication.user_directory:
        class: OpenConext\EngineBlockBundle\Authentication\Service\UserService
        arguments:
            - "@engineblock.repository.user"

    engineblock.features:
        class: OpenConext\EngineBlockBundle\Configuration\FeatureConfiguration
        arguments:
            - # replaced in the extension

    engineblock.error_feedback:
        class: OpenConext\EngineBlockBundle\Configuration\ErrorFeedbackConfiguration
        arguments:
            - "@translator"

    engineblock.pdp.pdp_client:
        class: OpenConext\EngineBlockBundle\Pdp\PdpClient
        arguments:
            - "@engineblock.pdp.http_client"
            - "%pdp.policy_decision_point_path%"

    engineblock.pdp.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.pdp.guzzle_http_client"

    engineblock.pdp.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - base_uri: "%pdp.host%"
              auth: ["%pdp.username%", "%pdp.password%", "Basic"]
              # Verify CAs for certificates for prod, but not for other environments
              # as we are working with self signed signatures
              verify: "@=service('kernel').getEnvironment() === 'prod'"

    engineblock.authentication.authentication_loop_guard:
        class: OpenConext\EngineBlockBundle\Authentication\AuthenticationLoopGuard
        arguments:
            - "%maximum_authentication_procedures_allowed%"
            - "%time_frame_for_authentication_loop_in_seconds%"

    engineblock.language_support_provider:
        class: OpenConext\EngineBlockBundle\Localization\LanguageSupportProvider
        arguments:
            - ['en', 'nl', 'pt']
            - '%enabled_languages%'

    engineblock.locale_provider:
        class: OpenConext\EngineBlockBundle\Localization\LocaleProvider
        arguments:
            - '@engineblock.language_support_provider'
            - '%kernel.default_locale%'

    engineblock.url_provider:
        class: OpenConext\EngineBlockBundle\Url\UrlProvider
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'

    engineblock.locale.cookie_factory:
        class: OpenConext\EngineBlockBundle\Http\Cookies\CookieFactory
        arguments:
            - 'lang'
            - '%cookie.locale.domain%'
            - '%cookie.locale.expiry%'
            - '%cookie.locale.http_only%'
            - '%cookie.locale.secure%'

    engineblock.attribute_aggregation.client:
        class: OpenConext\EngineBlockBundle\AttributeAggregation\AttributeAggregationClient
        arguments:
            - "@engineblock.attribute_aggregation.http_client"
            - "%attribute_aggregation.base_url%"

    engineblock.attribute_aggregation.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.attribute_aggregation.guzzle_http_client"

    engineblock.attribute_aggregation.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - auth: ["%attribute_aggregation.username%", "%attribute_aggregation.password%", "Basic"]

    engineblock.metadata.repository.cached_doctrine:
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\CachedDoctrineMetadataRepository
        arguments:
            - "@engineblock.metadata.repository.doctrine"

    engineblock.metadata.repository.idps_metadata:
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\IdpsMetadataRepository
        arguments:
            - "@engineblock.metadata.repository.cached_doctrine"
            - "@engineblock.factory.identity_provider_factory"
            - "@engineblock.url_provider"

    OpenConext\EngineBlock\Metadata\MetadataRepository\MetadataRepositoryInterface: '@engineblock.metadata.repository.cached_doctrine'

    engineblock.metadata.repository.doctrine:
        public: false
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\DoctrineMetadataRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@engineblock.repository.service_provider"
            - "@engineblock.repository.identity_provider"

    engineblock.metadata_push.repository.doctrine:
        public: false
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\DoctrineMetadataPushRepository
        arguments:
            - "@doctrine.orm.entity_manager"

    engineblock.metadata.push_metadata_assembler:
        public: false
        class: OpenConext\EngineBlock\Metadata\Entity\Assembler\PushMetadataAssembler
        arguments:
            - "@engineblock.validator.allowed_scheme_validator"
            - "@engineblock.compat.logger"

    OpenConext\EngineBlock\Metadata\X509\KeyPairFactory:
        arguments:
            - '%encryption_keys%'

    engineblock.validator.allowed_scheme_validator:
        class: OpenConext\EngineBlock\Validator\AllowedSchemeValidator
        arguments:
            - "%allowed_acs_location_schemes%"

    engineblock.validator.saml_binding_validator:
        class: OpenConext\EngineBlock\Validator\SamlBindingValidator

    engineblock.validator.acs_request_validator:
        class: OpenConext\EngineBlock\Validator\AcsRequestValidator

    engineblock.validator.sso_request_validator:
        class: OpenConext\EngineBlock\Validator\SsoRequestValidator

    engineblock.validator.unsolicited_sso_request_validator:
        class: OpenConext\EngineBlock\Validator\UnsolicitedSsoRequestValidator

    engineblock.validator.saml_response_validator:
        class: OpenConext\EngineBlock\Validator\SamlResponseValidator

    OpenConext\EngineBlockBundle\Authentication\Service\SamlResponseHelper:
        class: OpenConext\EngineBlockBundle\Authentication\Service\SamlResponseHelper
        arguments:
            - "@engineblock.metadata.repository.cached_doctrine"

    engineblock.twig.extension.debug:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Debug
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.feedback:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Feedback
        arguments:
            - "@engineblock.compat.application"
            - "@engineblock.error_feedback"
            - "@engineblock.compat.repository.metadata"
            - "@OpenConext\\EngineBlockBundle\\Authentication\\Service\\SamlResponseHelper"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.global_site_notice:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\GlobalSiteNotice
        arguments:
            - "%global.site_notice.show%"
            - "%global.site_notice.allowed.tags%"
            - "@translator"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.i18n:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\I18n
        arguments:
            - "@translator"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.locale:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Locale
        arguments:
            - "@request_stack"
            - "@engineblock.language_support_provider"
            - "%locale%"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.metadata:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Metadata
        arguments:
            - "@engineblock.compat.metadata.definitions"
            - "@translator"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.wayf:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Wayf
        arguments:
            - "@request_stack"
            - "@translator"
        tags:
             - { name: 'twig.extension' }
