services:
    openconext.monitor.database_health_check:
        class: OpenConext\EngineBlockBundle\HealthCheck\DoctrineConnectionHealthCheck
        arguments:
            - "%monitor_database_health_check_query%"
        calls:
            - [ setEntityManager, ['@?doctrine.orm.entity_manager']]
        tags:
            - { name: openconext.monitor.health_check }

    engineblock.minimum_execution_time_on_invalid_received_response:
        class: OpenConext\EngineBlockBundle\Value\ExecutionTime
        factory: [ OpenConext\EngineBlockBundle\Value\ExecutionTime, "of" ]
        arguments:
            - "%minimum_execution_time_on_invalid_received_response%"

    engineblock.request.request_id_generator:
        public: false
        class: OpenConext\EngineBlock\Request\UniqidGenerator

    engineblock.request.request_id:
        class: OpenConext\EngineBlock\Request\RequestId
        arguments:
            - "@engineblock.request.request_id_generator"
        public: true

    engineblock.security.http_basic_entry_point:
        class: OpenConext\EngineBlockBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - "engine-api.%domain%"

    engineblock.service.consent:
        class: OpenConext\EngineBlock\Service\ConsentService
        arguments:
            - "@engineblock.repository.consent"
            - "@engineblock.service.metadata"
            - "@engineblock.compat.logger"

    engineblock.service.deprovision:
        class: OpenConext\EngineBlock\Service\DeprovisionService
        arguments:
            - "@engineblock.repository.consent"
            - "@engineblock.authentication.user_directory"
            - "@engineblock.repository.saml_persistent_id"
            - "@engineblock.repository.service_provider_uuid"

    engineblock.service.metadata:
        class: OpenConext\EngineBlock\Service\MetadataService
        arguments:
            - "@engineblock.compat.repository.metadata"
            - "@engineblock.compat.logger"

    engineblock.authentication.user_directory:
        class: OpenConext\EngineBlockBundle\Authentication\Service\UserService
        arguments:
            - "@engineblock.repository.user"

    engineblock.features:
        class: OpenConext\EngineBlockBundle\Configuration\FeatureConfiguration
        arguments:
            - # replaced in the extension

    engineblock.pdp.pdp_client:
        class: OpenConext\EngineBlockBundle\Pdp\PdpClient
        arguments:
            - "@engineblock.pdp.http_client"
            - "%pdp.policy_decision_point_path%"

    engineblock.pdp.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.pdp.guzzle_http_client"

    engineblock.pdp.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - base_uri: "%pdp.host%"
              auth: ["%pdp.username%", "%pdp.password%", "Basic"]
              # Verify CAs for certificates for prod, but not for other environments
              # as we are working with self signed signatures
              verify: "@=service('kernel').getEnvironment() === 'prod'"

    engineblock.authentication.authentication_loop_guard:
        class: OpenConext\EngineBlockBundle\Authentication\AuthenticationLoopGuard
        arguments:
            - "%maximum_authentication_procedures_allowed%"
            - "%time_frame_for_authentication_loop_in_seconds%"

    engineblock.locale_provider:
        class: OpenConext\EngineBlockBundle\Localization\LocaleProvider
        arguments:
            - ['en', 'nl']
            - '%kernel.default_locale%'

    engineblock.locale.cookie_factory:
        class: OpenConext\EngineBlockBundle\Http\Cookies\CookieFactory
        arguments:
            - 'lang'
            - '%cookie.locale.domain%'
            - '%cookie.locale.expiry%'
            - '%cookie.locale.http_only%'
            - '%cookie.locale.secure%'

    engineblock.attribute_aggregation.client:
        class: OpenConext\EngineBlockBundle\AttributeAggregation\AttributeAggregationClient
        arguments:
            - "@engineblock.attribute_aggregation.http_client"
            - "%attribute_aggregation.base_url%"

    engineblock.attribute_aggregation.http_client:
        class: OpenConext\EngineBlock\Http\HttpClient
        arguments:
            - "@engineblock.attribute_aggregation.guzzle_http_client"

    engineblock.attribute_aggregation.guzzle_http_client:
        class: GuzzleHttp\Client
        arguments:
            - auth: ["%attribute_aggregation.username%", "%attribute_aggregation.password%", "Basic"]

    engineblock.metadata.repository.cached_doctrine:
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\CachedDoctrineMetadataRepository
        arguments:
            - "@engineblock.metadata.repository.doctrine"

    engineblock.metadata.repository.doctrine:
        public: false
        class: OpenConext\EngineBlock\Metadata\MetadataRepository\DoctrineMetadataRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@engineblock.repository.service_provider"
            - "@engineblock.repository.identity_provider"

    engineblock.metadata.push_metadata_assembler:
        public: false
        class: OpenConext\EngineBlock\Metadata\Entity\Assembler\PushMetadataAssembler
        arguments:
            - "@engineblock.validator.allowed_scheme_validator"

    engineblock.validator.allowed_scheme_validator:
        class: OpenConext\EngineBlock\Validator\AllowedSchemeValidator
        arguments:
            - "%allowed_acs_location_schemes%"

    engineblock.twig.extension.debug:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Debug
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.feedback:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Feedback
        arguments:
            - "@engineblock.compat.application"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.i18n:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\I18n
        arguments:
            - "@translator"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.locale:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Locale
        arguments:
            - "@request_stack"
            - "%locale%"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.metadata:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Metadata
        arguments:
            - "@engineblock.compat.metadata.definitions"
            - "@translator"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.user_agent:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\UserAgent
        arguments:
            - "@request_stack"
        tags:
             - { name: 'twig.extension' }

    engineblock.twig.extension.wayf:
        class: OpenConext\EngineBlockBundle\Twig\Extensions\Extension\Wayf
        arguments:
            - "@request_stack"
            - "@translator"
        tags:
             - { name: 'twig.extension' }
