authentication_wayf_process_wayf:
    path:   /authentication/idp/process-wayf
    methods: [GET,POST] # verify GET?
    defaults:
        _controller: engineblock.controller.authentication.wayf:processWayfAction

authentication_wayf_help_discover:
    path:   /authentication/idp/help-discover
    methods: [GET]
    defaults:
        _controller: engineblock.controller.authentication.wayf:helpDiscoverAction
