services:
    eb.compat.application:
        class: EngineBlock_ApplicationSingleton
        factory:  [EngineBlock_ApplicationSingleton, getInstance]

    eb.compat.config:
        class: Zend_Config
        factory: ["@eb.compat.application", getConfiguration]

    eb.compat.di_container:
        public: false
        class: EngineBlock_Application_DiContainer
        factory: ["@eb.compat.application", getDiContainer]

    eb.compat.doctrine.entity_manager:
        public: false
        class: Doctrine\ORM\EntityManager
        factory: [@eb.compat.di_container, getEntityManager]

    eb.compat.doctrine.dbal_connection:
        public: false
        class: Doctrine\DBAL\Connection
        factory: [@eb.compat.doctrine.entity_manager, getConnection]

    eb.compat.view:
        class: EngineBlock_View
        calls:
            - ['setLayout', [@eb.compat.layout]]

    eb.compat.logger:
        class: Monolog\Logger
        factory:  [EngineBlock_ApplicationSingleton, getLog]

    eb.compat.layout:
        class: Zend_Layout
        calls:
            - ['setLayout',       ["@=service('eb.compat.config').defaults.layout"]]
            - ['setLayoutPath',   ["%kernel.root_dir%/Resources/views/layouts/scripts/"]]
            - ['setViewBasePath', ["%kernel.root_dir%/Resources/views/modules/"]]
        properties:
            title: "@=service('eb.compat.config').defaults.title"
            header: "@=service('eb.compat.config').defaults.header"

### Bridge classes

    eb.bridge.error_reporter:
        class: OpenConext\EngineBlock\CompatibilityBundle\Bridge\ErrorReporter
        arguments:
            - @eb.compat.application
            - @eb.compat.logger

    eb.bridge.mailer:
        class: OpenConext\EngineBlock\CompatibilityBundle\Bridge\ZendMailSender
        arguments:
            - "@=service('eb.compat.config').email.help"
            - @eb.compat.logger
