feedback_unknown_error:
    path: '/feedback/unknown-error'
    methods: [GET]
    defaults: { _controller: engineblock.controller.authentication.feedback:unknownErrorAction }

authentication_feedback_unable_to_receive_message:
    path:       '/authentication/feedback/unable-to-receive-message'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unableToReceiveMessageAction }

authentication_feedback_session_lost:
    path:       '/authentication/feedback/session-lost'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:sessionLostAction }

authentication_feedback_session_not_started:
    path:       '/authentication/feedback/session-not-started'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:sessionNotStartedAction }

authentication_feedback_no_idps:
    path:       '/authentication/feedback/no-idps'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:noIdpsAction }

authentication_feedback_invalid_acs_location:
    path:       '/authentication/feedback/invalidAcsLocation'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:invalidAcsLocationAction }

authentication_feedback_unsupported_signature_method:
    path:       '/authentication/feedback/unsupportedSignatureMethod'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unsupportedSignatureMethodAction }

authentication_feedback_unsupported_acs_location_uri_scheme:
    path:       '/authentication/feedback/unsupported-acs-location-scheme'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unsupportedAcsLocationSchemeAction }

authentication_feedback_unknown_service_provider:
    path:       '/authentication/feedback/unknown-service-provider'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unknownServiceProviderAction }

authentication_feedback_unknown_identity_provider:
    path:       '/authentication/feedback/unknown-identity-provider'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unknownIdentityProviderAction }

authentication_feedback_missing_required_fields:
    path:       '/authentication/feedback/missing-required-fields'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:missingRequiredFieldsAction }

authentication_authn_context_class_ref_blacklisted:
    path:       '/authentication/feedback/authn-context-class-ref-blacklisted'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:authnContextClassRefBlacklistedAction }

authentication_invalid_mfa_authn_context_class_ref:
    path:       '/authentication/feedback/invalid-mfa-authn-context-class-ref'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:invalidMfAuthnContextClassRefAction }

authentication_feedback_invalid_attribute_value:
    path:       '/authentication/feedback/invalid-attribute-value'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:invalidAttributeValueAction }

authentication_feedback_custom:
    path:       '/authentication/feedback/custom'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:customAction }

authentication_feedback_invalid_acs_binding:
    path:       '/authentication/feedback/invalid-acs-binding'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:invalidAcsBindingAction }

authentication_feedback_received_error_status_code:
    path:       '/authentication/feedback/received-error-status-code'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:receivedErrorStatusCodeAction }

authentication_feedback_signature_verification_failed:
    path:       '/authentication/feedback/received-invalid-signed-response'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:signatureVerificationFailedAction }

authentication_feedback_verification_failed:
    path:       '/authentication/feedback/received-invalid-response'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:receivedInvalidResponseAction }

authentication_feedback_unknown_requesterid_in_authnrequest:
    path:       '/authentication/feedback/unknown_requesterid_in_authnrequest'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unknownRequesterIdInAuthnRequestAction }

authentication_feedback_pep_violation:
    path:       '/authentication/feedback/authorization-policy-violation'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:authorizationPolicyViolationAction }

authentication_feedback_unknown_preselected_idp:
    path:       '/authentication/feedback/unknown-preselected-idp'
    methods:    [GET]
    defaults:   { _controller: engineblock.controller.authentication.feedback:unknownPreselectedIdpAction }

authentication_feedback_stuck_in_authentication_loop:
    path:       '/authentication/feedback/stuck-in-authentication-loop'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:stuckInAuthenticationLoopAction }

authentication_feedback_no_authentication_request_received:
    path:       '/authentication/feedback/invalid-request-method-on-sso'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:noAuthenticationRequestReceivedAction }

authentication_feedback_response_clock_issue:
    path:       '/authentication/feedback/clock-issue'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:clockIssueAction }

authentication_feedback_stepup_callout_user_cancelled:
    path:       '/authentication/feedback/stepup-callout-user-cancelled'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:stepupCalloutUserCancelledAction }

authentication_feedback_stepup_callout_unmet_loa:
    path:       '/authentication/feedback/stepup-callout-unmet-loa'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:stepupCalloutUnmetLoaAction }

authentication_feedback_stepup_callout_unknown:
    path:       '/authentication/feedback/stepup-callout-unknown'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:stepupCalloutUnknownAction }

authentication_feedback_metadata_entity_not_found:
    path:       '/authentication/feedback/metadata-entity-not-found'
    methods:    [GET]
    defaults:    { _controller: engineblock.controller.authentication.feedback:metadataEntityNotFoundAction }
