authentication_sp_consume_assertion:
    path:     /authentication/sp/consume-assertion
    methods:  [POST]
    defaults:
        _controller: engineblock.controller.authentication.service_provider:consumeAssertionAction

authentication_sp_process_consent:
    path:     /authentication/sp/process-consent
    methods:  [GET,POST]
    defaults:
        _controller: engineblock.controller.authentication.service_provider:processConsentAction

# Stepup authentication
authentication_stepup_consume_assertion:
    path:     /authentication/stepup/consume-assertion
    methods:  [POST]
    defaults:
        _controller: engineblock.controller.authentication.stepup:consumeAssertionAction
